import {
  ACTION_ALLOW_SKIPPED_DEFAULT,
  ACTION_CONFIG_PATH_DEFAULT,
  ACTION_OMITTED_TOKEN_DEFAULT,
  ACTION_OUTPUT_ACTION_DEFAULT,
} from "../types.ts";
import { isFlattenedActionInputName } from "./flatten.ts";

export const ACTION_YML_FILENAME = "action.yml";
export const ACTION_YML_NAME = "Profile Bits widgets";
export const ACTION_YML_DESCRIPTION =
  "Generate GitHub profile widgets from committed yaml.";
export const ACTION_YML_BRANDING_ICON = "layout";
export const ACTION_YML_BRANDING_COLOR = "blue";
export const ACTION_YML_RUNS_USING = "node24";
export const ACTION_YML_MAIN = "dist/index.js";

/** Workflow expression default for `user` (see ACTION_USER_DEFAULT). */
export const ACTION_USER_YAML_DEFAULT = `\${{ github.repository_owner }}`;

export type ActionInputSpec = {
  name: string;
  description: string;
  default?: string;
};

export const THIN_ACTION_INPUTS: readonly ActionInputSpec[] = [
  {
    name: "user",
    description:
      "GitHub login to render widgets for. Defaults to the repository owner.",
    default: ACTION_USER_YAML_DEFAULT,
  },
  {
    name: "github_token",
    description:
      "GitHub token for API requests. Omitted uses the workflow token. Empty or whitespace fails the job.",
    default: ACTION_OMITTED_TOKEN_DEFAULT,
  },
  {
    name: "committer_token",
    description:
      "GitHub token for git commit, pull-request, and gist output. Defaults to the workflow token.",
    default: ACTION_OMITTED_TOKEN_DEFAULT,
  },
  {
    name: "config",
    description:
      "Path to the profile-bits yaml config (SSOT for plugin and widget options).",
    default: ACTION_CONFIG_PATH_DEFAULT,
  },
  {
    name: "plugin_github",
    description:
      "Enable the github pack (stats, languages) only when the config file is absent. Ignored when the config file exists.",
  },
  {
    name: "format",
    description:
      "Optional output format override (svg, png, jpeg, webp, ico, gif, apng).",
  },
  {
    name: "theme",
    description: "Optional theme override (light or dark).",
  },
  {
    name: "output_pair",
    description: "Optional override to write both filename and filename-dark.",
  },
  {
    name: "animated",
    description: "Optional override for animated output.",
  },
  {
    name: "output_action",
    description:
      "How to publish widget files (none, commit, pull-request, gist). gist is SVG only.",
    default: ACTION_OUTPUT_ACTION_DEFAULT,
  },
  {
    name: "committer_branch",
    description:
      "Branch to commit widget files to. Defaults to the current branch.",
  },
  {
    name: "committer_gist",
    description: "Gist id to update when output_action is gist.",
  },
  {
    name: "output_condition",
    description: "When to publish output (always or data-changed).",
  },
  {
    name: "timezone",
    description: "Optional timezone override (IANA name, for example UTC).",
  },
  {
    name: "dry_run",
    description:
      "Render widgets without committing, opening a pull request, or updating a gist.",
  },
  {
    name: "allow_skipped",
    description:
      "When true, the job may succeed if every github widget is skipped.",
    default: String(ACTION_ALLOW_SKIPPED_DEFAULT),
  },
];

export const THIN_ACTION_INPUT_NAMES: readonly string[] =
  THIN_ACTION_INPUTS.map((input) => input.name);

function quoteYamlDouble(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function yamlDefaultRhs(value: string): string {
  if (value.startsWith(`\${{`) && value.endsWith("}}")) {
    return value;
  }
  if (/^[A-Za-z0-9_.\\/-]+$/.test(value)) {
    return value;
  }
  return quoteYamlDouble(value);
}

export function renderActionYml(
  inputs: readonly ActionInputSpec[] = THIN_ACTION_INPUTS,
): string {
  const inputBlocks = inputs.map((input) => {
    const lines = [
      `  ${input.name}:`,
      `    description: ${quoteYamlDouble(input.description)}`,
    ];
    if (input.default !== undefined) {
      lines.push(`    default: ${yamlDefaultRhs(input.default)}`);
    }
    return lines.join("\n");
  });

  return [
    "# Generated by `pnpm generate-action`. Do not edit by hand.",
    `name: ${ACTION_YML_NAME}`,
    `description: ${quoteYamlDouble(ACTION_YML_DESCRIPTION)}`,
    "branding:",
    `  icon: ${ACTION_YML_BRANDING_ICON}`,
    `  color: ${ACTION_YML_BRANDING_COLOR}`,
    "inputs:",
    ...inputBlocks,
    "runs:",
    `  using: ${ACTION_YML_RUNS_USING}`,
    `  main: ${ACTION_YML_MAIN}`,
    "",
  ].join("\n");
}

export function generateActionYml(): string {
  return renderActionYml(THIN_ACTION_INPUTS);
}

export function flattenedGeneratedInputNames(
  inputs: readonly ActionInputSpec[] = THIN_ACTION_INPUTS,
): string[] {
  return inputs
    .map((input) => input.name)
    .filter((name) => isFlattenedActionInputName(name))
    .sort();
}
