import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const AYU_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "ayu-dark",
    family: "ayu",
    label: "Dark",
    polarity: "dark",
    pair: "ayu-light",
    license: "MIT",
    sourceUrl: "https://github.com/ayu-theme/ayu-colors",
    swatches: {
      "ui-bg": "#0d1017",
      "editor-bg": "#10141c",
      "editor-fg": "#bfbdb6",
      "ui-fg": "#555e73",
      "ui-line": "#1b1f29",
      "panel-bg": "#141821",
      accent: "#e6b450",
      tag: "#39bae6",
      func: "#ffb454",
      entity: "#59c2ff",
      string: "#aad94c",
      keyword: "#ff8f40",
      constant: "#d2a6ff",
      operator: "#f29668",
      markup: "#f07178",
    },
    roles: {
      bg: "ui-bg",
      card: "editor-bg",
      text: "editor-fg",
      muted: "ui-fg",
      accent: "accent",
      border: "ui-line",
      font: THEME_FONT,
    },
  },
  {
    id: "ayu-mirage",
    family: "ayu",
    label: "Mirage",
    polarity: "dark",
    pair: "ayu-light",
    license: "MIT",
    sourceUrl: "https://github.com/ayu-theme/ayu-colors",
    swatches: {
      "ui-bg": "#1f2430",
      "editor-bg": "#242936",
      "editor-fg": "#cccac2",
      "ui-fg": "#707a8c",
      "ui-line": "#171b24",
      "panel-bg": "#282e3b",
      accent: "#ffcc66",
    },
    roles: {
      bg: "ui-bg",
      card: "editor-bg",
      text: "editor-fg",
      muted: "ui-fg",
      accent: "accent",
      border: "ui-line",
      font: THEME_FONT,
    },
  },
  {
    id: "ayu-light",
    family: "ayu",
    label: "Light",
    polarity: "light",
    pair: "ayu-dark",
    license: "MIT",
    sourceUrl: "https://github.com/ayu-theme/ayu-colors",
    swatches: {
      "ui-bg": "#f8f9fa",
      "editor-bg": "#fcfcfc",
      "editor-fg": "#5c6166",
      "ui-fg": "#828e9f",
      "ui-line": "#6b7d8f",
      "panel-bg": "#fafafa",
      accent: "#f29718",
    },
    roles: {
      bg: "ui-bg",
      card: "editor-bg",
      text: "editor-fg",
      muted: "ui-fg",
      accent: "accent",
      border: "ui-line",
      font: THEME_FONT,
    },
  },
];
