import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const BLULOCO_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "bluloco-dark",
    family: "bluloco",
    label: "Dark",
    polarity: "dark",
    pair: "bluloco-light",
    license: "LGPL-3.0",
    sourceUrl: "https://github.com/uloco/theme-bluloco-dark",
    swatches: {
      background: "#282c34",
      foreground: "#abb2bf",
      comment: "#636d83",
      keyword: "#10b1fe",
      function: "#3fc56b",
      property: "#ce9887",
      string: "#f9c859",
      number: "#ff78f8",
      constant: "#9f7efe",
      class: "#ff6480",
      operator: "#7a82da",
      widget: "#22252a",
      border: "#3d434f",
    },
    roles: {
      bg: "background",
      card: "widget",
      text: "foreground",
      muted: "comment",
      accent: "keyword",
      border: "border",
      font: THEME_FONT,
    },
  },
  {
    id: "bluloco-light",
    family: "bluloco",
    label: "Light",
    polarity: "light",
    pair: "bluloco-dark",
    license: "LGPL-3.0",
    sourceUrl: "https://github.com/uloco/theme-bluloco-light",
    swatches: {
      background: "#f9f9f9",
      foreground: "#383a42",
      comment: "#a0a1a7",
      keyword: "#0098dd",
      function: "#23974a",
      property: "#a05a48",
      string: "#c5a332",
      number: "#ce33c0",
      constant: "#823ff1",
      class: "#d52753",
      operator: "#7a82da",
      widget: "#e8e8e8",
      border: "#d5d7d8",
    },
    roles: {
      bg: "background",
      card: "widget",
      text: "foreground",
      muted: "comment",
      accent: "keyword",
      border: "border",
      font: THEME_FONT,
    },
  },
];
