import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const DRACULA_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "dracula",
    family: "dracula",
    label: "Dracula",
    polarity: "dark",
    pair: "dracula-alucard",
    license: "MIT",
    sourceUrl: "https://draculatheme.com/spec",
    swatches: {
      background: "#282a36",
      "current-line": "#6272a4",
      selection: "#44475a",
      foreground: "#f8f8f2",
      comment: "#6272a4",
      cyan: "#8be9fd",
      green: "#50fa7b",
      orange: "#ffb86c",
      pink: "#ff79c6",
      purple: "#bd93f9",
      red: "#ff5555",
      yellow: "#f1fa8c",
    },
    roles: {
      bg: "background",
      card: "selection",
      text: "foreground",
      muted: "comment",
      accent: "purple",
      border: "current-line",
      font: THEME_FONT,
    },
  },
  {
    id: "dracula-alucard",
    family: "dracula",
    label: "Alucard",
    polarity: "light",
    pair: "dracula",
    license: "MIT",
    sourceUrl: "https://draculatheme.com/spec",
    swatches: {
      background: "#fffbeb",
      "current-line": "#6c664b",
      selection: "#cfcfde",
      foreground: "#1f1f1f",
      comment: "#6c664b",
      cyan: "#036a96",
      green: "#14710a",
      orange: "#a34d14",
      pink: "#a3144d",
      purple: "#644ac9",
      red: "#cb3a2a",
      yellow: "#846e15",
    },
    roles: {
      bg: "background",
      card: "selection",
      text: "foreground",
      muted: "comment",
      accent: "purple",
      border: "current-line",
      font: THEME_FONT,
    },
  },
];
