import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const EVERFOREST_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "everforest-dark",
    family: "everforest",
    label: "Dark",
    polarity: "dark",
    pair: "everforest-light",
    license: "MIT",
    sourceUrl: "https://github.com/sainnhe/everforest",
    swatches: {
      bg_dim: "#232a2e",
      bg0: "#2d353b",
      bg1: "#343f44",
      bg2: "#3d484d",
      bg3: "#475258",
      bg4: "#4f585e",
      fg: "#d3c6aa",
      red: "#e67e80",
      orange: "#e69875",
      yellow: "#dbbc7f",
      green: "#a7c080",
      aqua: "#83c092",
      blue: "#7fbbb3",
      purple: "#d699b6",
      grey0: "#7a8478",
      grey1: "#859289",
      grey2: "#9da9a0",
    },
    roles: {
      bg: "bg0",
      card: "bg1",
      text: "fg",
      muted: "grey1",
      accent: "blue",
      border: "bg4",
      font: THEME_FONT,
    },
  },
  {
    id: "everforest-light",
    family: "everforest",
    label: "Light",
    polarity: "light",
    pair: "everforest-dark",
    license: "MIT",
    sourceUrl: "https://github.com/sainnhe/everforest",
    swatches: {
      bg_dim: "#efebd4",
      bg0: "#fdf6e3",
      bg1: "#f4f0d9",
      bg2: "#efebd4",
      bg3: "#e6e2cc",
      bg4: "#e0dcc7",
      fg: "#5c6a72",
      red: "#f85552",
      orange: "#f57d26",
      yellow: "#dfa000",
      green: "#8da101",
      aqua: "#35a77c",
      blue: "#3a94c5",
      purple: "#df69ba",
      grey0: "#a6b0a0",
      grey1: "#939f91",
      grey2: "#829181",
    },
    roles: {
      bg: "bg0",
      card: "bg1",
      text: "fg",
      muted: "grey1",
      accent: "blue",
      border: "bg4",
      font: THEME_FONT,
    },
  },
];
