import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const HORIZON_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "horizon-dark",
    family: "horizon",
    label: "Dark",
    polarity: "dark",
    pair: "horizon-light",
    license: "MIT",
    sourceUrl: "https://github.com/jolaleye/horizon-theme-vscode",
    swatches: {
      background: "#1c1e26",
      foreground: "#d5d8da",
      widget: "#232530",
      accent: "#e95378",
      "syntax-gray": "#6c6f93",
      focus: "#1a1c23",
      shadow: "#16161c",
      error: "#f43e5c",
    },
    roles: {
      bg: "background",
      card: "widget",
      text: "foreground",
      muted: "syntax-gray",
      accent: "accent",
      border: "focus",
      font: THEME_FONT,
    },
  },
  {
    id: "horizon-light",
    family: "horizon",
    label: "Light",
    polarity: "light",
    pair: "horizon-dark",
    license: "MIT",
    sourceUrl: "https://github.com/jolaleye/horizon-theme-vscode",
    swatches: {
      background: "#fdf0ed",
      foreground: "#06060c",
      widget: "#fadad1",
      accent: "#e84a72",
      "syntax-gray": "#6c6f93",
      button: "#f9cbbe",
      error: "#f43e5c",
    },
    roles: {
      bg: "background",
      card: "widget",
      text: "foreground",
      muted: "syntax-gray",
      accent: "accent",
      border: "button",
      font: THEME_FONT,
    },
  },
];
