import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const ICEBERG_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "iceberg-dark",
    family: "iceberg",
    label: "Dark",
    polarity: "dark",
    pair: "iceberg-light",
    license: "MIT",
    sourceUrl: "https://github.com/cocopon/iceberg.vim",
    swatches: {
      background: "#161821",
      foreground: "#c6c8d1",
      comment: "#6b7089",
      line: "#1e2132",
      popup: "#3d425b",
      function: "#84a0c6",
      cursorline: "#2a3158",
      linenumber: "#444b71",
      statusline: "#818596",
      split: "#0f1117",
    },
    roles: {
      bg: "background",
      card: "line",
      text: "foreground",
      muted: "comment",
      accent: "function",
      border: "cursorline",
      font: THEME_FONT,
    },
  },
  {
    id: "iceberg-light",
    family: "iceberg",
    label: "Light",
    polarity: "light",
    pair: "iceberg-dark",
    license: "MIT",
    sourceUrl: "https://github.com/cocopon/iceberg.vim",
    swatches: {
      background: "#e8e9ec",
      foreground: "#33374c",
      comment: "#8389a3",
      line: "#dcdfe7",
      popup: "#cad0de",
      function: "#2d539e",
      cursorline: "#cad0de",
      linenumber: "#9fa7bd",
      statusline: "#757ca3",
      identifier: "#3f83a6",
    },
    roles: {
      bg: "background",
      card: "line",
      text: "foreground",
      muted: "comment",
      accent: "function",
      border: "popup",
      font: THEME_FONT,
    },
  },
];
