import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const NORD_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "nord",
    family: "nord",
    label: "Nord",
    polarity: "dark",
    pair: "nord-light",
    license: "MIT",
    sourceUrl: "https://www.nordtheme.com",
    swatches: {
      "polar-night-0": "#2e3440",
      "polar-night-1": "#3b4252",
      "polar-night-2": "#434c5e",
      "polar-night-3": "#4c566a",
      "snow-storm-0": "#d8dee9",
      "snow-storm-1": "#e5e9f0",
      "snow-storm-2": "#eceff4",
      "frost-0": "#8fbcbb",
      "frost-1": "#88c0d0",
      "frost-2": "#81a1c1",
      "frost-3": "#5e81ac",
      "aurora-red": "#bf616a",
      "aurora-orange": "#d08770",
      "aurora-yellow": "#ebcb8b",
      "aurora-green": "#a3be8c",
      "aurora-purple": "#b48ead",
      nord0: "#2e3440",
      nord1: "#3b4252",
      nord2: "#434c5e",
      nord3: "#4c566a",
      nord4: "#d8dee9",
      nord5: "#e5e9f0",
      nord6: "#eceff4",
      nord7: "#8fbcbb",
      nord8: "#88c0d0",
      nord9: "#81a1c1",
      nord10: "#5e81ac",
      nord11: "#bf616a",
      nord12: "#d08770",
      nord13: "#ebcb8b",
      nord14: "#a3be8c",
      nord15: "#b48ead",
    },
    roles: {
      bg: "polar-night-0",
      card: "polar-night-1",
      text: "snow-storm-2",
      muted: "snow-storm-0",
      accent: "frost-1",
      border: "polar-night-2",
      font: THEME_FONT,
    },
  },
  {
    id: "nord-light",
    family: "nord",
    label: "Nord Light",
    polarity: "light",
    pair: "nord",
    license: "MIT",
    sourceUrl: "https://www.nordtheme.com",
    swatches: {
      "polar-night-0": "#2e3440",
      "polar-night-1": "#3b4252",
      "polar-night-2": "#434c5e",
      "polar-night-3": "#4c566a",
      "snow-storm-0": "#d8dee9",
      "snow-storm-1": "#e5e9f0",
      "snow-storm-2": "#eceff4",
      "frost-0": "#8fbcbb",
      "frost-1": "#88c0d0",
      "frost-2": "#81a1c1",
      "frost-3": "#5e81ac",
      "aurora-red": "#bf616a",
      "aurora-orange": "#d08770",
      "aurora-yellow": "#ebcb8b",
      "aurora-green": "#a3be8c",
      "aurora-purple": "#b48ead",
      nord0: "#2e3440",
      nord1: "#3b4252",
      nord2: "#434c5e",
      nord3: "#4c566a",
      nord4: "#d8dee9",
      nord5: "#e5e9f0",
      nord6: "#eceff4",
      nord7: "#8fbcbb",
      nord8: "#88c0d0",
      nord9: "#81a1c1",
      nord10: "#5e81ac",
      nord11: "#bf616a",
      nord12: "#d08770",
      nord13: "#ebcb8b",
      nord14: "#a3be8c",
      nord15: "#b48ead",
    },
    roles: {
      bg: "snow-storm-2",
      card: "snow-storm-1",
      text: "polar-night-0",
      muted: "polar-night-3",
      accent: "frost-3",
      border: "snow-storm-0",
      font: THEME_FONT,
    },
  },
];
