import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const ONE_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "one-dark",
    family: "one",
    label: "One Dark",
    polarity: "dark",
    pair: "one-light",
    license: "MIT",
    sourceUrl: "https://github.com/atom/one-dark-syntax",
    swatches: {
      "syntax-bg": "#282c34",
      "syntax-fg": "#abb2bf",
      "mono-1": "#abb2bf",
      "mono-2": "#828997",
      "mono-3": "#5c6370",
      "hue-1": "#56b6c2",
      "hue-2": "#61afef",
      "hue-3": "#c678dd",
      "hue-4": "#98c379",
      "hue-5": "#e06c75",
      "hue-5-2": "#be5046",
      "hue-6": "#d19a66",
      "hue-6-2": "#e5c07b",
      "syntax-accent": "#528bff",
    },
    roles: {
      bg: "syntax-bg",
      card: "syntax-bg",
      text: "mono-1",
      muted: "mono-3",
      accent: "hue-2",
      border: "mono-3",
      font: THEME_FONT,
    },
  },
  {
    id: "one-light",
    family: "one",
    label: "One Light",
    polarity: "light",
    pair: "one-dark",
    license: "MIT",
    sourceUrl: "https://github.com/atom/one-light-syntax",
    swatches: {
      "syntax-bg": "#fafafa",
      "syntax-fg": "#383a42",
      "mono-1": "#383a42",
      "mono-2": "#696c77",
      "mono-3": "#a0a1a7",
      "hue-1": "#0184bc",
      "hue-2": "#4078f2",
      "hue-3": "#a626a4",
      "hue-4": "#50a14f",
      "hue-5": "#e45649",
      "hue-5-2": "#ca1243",
      "hue-6": "#986801",
      "hue-6-2": "#c18401",
      "syntax-accent": "#526fff",
    },
    roles: {
      bg: "syntax-bg",
      card: "syntax-bg",
      text: "mono-1",
      muted: "mono-3",
      accent: "hue-2",
      border: "mono-3",
      font: THEME_FONT,
    },
  },
];
