import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const ROSE_PINE_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "rose-pine",
    family: "rose-pine",
    label: "Rosé Pine",
    polarity: "dark",
    pair: "rose-pine-dawn",
    license: "MIT",
    sourceUrl: "https://github.com/rose-pine/palette",
    swatches: {
      base: "#191724",
      surface: "#1f1d2e",
      overlay: "#26233a",
      muted: "#6e6a86",
      subtle: "#908caa",
      text: "#e0def4",
      love: "#eb6f92",
      gold: "#f6c177",
      rose: "#ebbcba",
      pine: "#31748f",
      foam: "#9ccfd8",
      iris: "#c4a7e7",
    },
    roles: {
      bg: "base",
      card: "surface",
      text: "text",
      muted: "muted",
      accent: "iris",
      border: "overlay",
      font: THEME_FONT,
    },
  },
  {
    id: "rose-pine-moon",
    family: "rose-pine",
    label: "Moon",
    polarity: "dark",
    pair: "rose-pine-dawn",
    license: "MIT",
    sourceUrl: "https://github.com/rose-pine/palette",
    swatches: {
      base: "#232136",
      surface: "#2a273f",
      overlay: "#393552",
      muted: "#6e6a86",
      subtle: "#908caa",
      text: "#e0def4",
      love: "#eb6f92",
      gold: "#f6c177",
      rose: "#ea9a97",
      pine: "#3e8fb0",
      foam: "#9ccfd8",
      iris: "#c4a7e7",
    },
    roles: {
      bg: "base",
      card: "surface",
      text: "text",
      muted: "muted",
      accent: "iris",
      border: "overlay",
      font: THEME_FONT,
    },
  },
  {
    id: "rose-pine-dawn",
    family: "rose-pine",
    label: "Dawn",
    polarity: "light",
    pair: "rose-pine",
    license: "MIT",
    sourceUrl: "https://github.com/rose-pine/palette",
    swatches: {
      base: "#faf4ed",
      surface: "#fffaf3",
      overlay: "#f2e9e1",
      muted: "#9893a5",
      subtle: "#797593",
      text: "#575279",
      love: "#b4637a",
      gold: "#ea9d34",
      rose: "#d7827e",
      pine: "#286983",
      foam: "#56949f",
      iris: "#907aa9",
    },
    roles: {
      bg: "base",
      card: "surface",
      text: "text",
      muted: "muted",
      accent: "iris",
      border: "overlay",
      font: THEME_FONT,
    },
  },
];
