import { THEME_FONT, type ThemeFlavor } from "../types.js";

export const TOKYO_NIGHT_FLAVORS: readonly ThemeFlavor[] = [
  {
    id: "tokyo-night",
    family: "tokyo-night",
    label: "Night",
    polarity: "dark",
    pair: "tokyo-night-day",
    license: "Apache-2.0",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
    swatches: {
      bg: "#1a1b26",
      bg_dark: "#16161e",
      bg_highlight: "#292e42",
      fg: "#c0caf5",
      fg_dark: "#a9b1d6",
      fg_gutter: "#3b4261",
      comment: "#565f89",
      dark3: "#545c7e",
      dark5: "#737aa2",
      blue: "#7aa2f7",
      cyan: "#7dcfff",
      magenta: "#bb9af7",
      purple: "#9d7cd8",
      orange: "#ff9e64",
      yellow: "#e0af68",
      green: "#9ece6a",
      teal: "#1abc9c",
      red: "#f7768e",
      terminal_black: "#414868",
    },
    roles: {
      bg: "bg",
      card: "bg_dark",
      text: "fg",
      muted: "comment",
      accent: "blue",
      border: "fg_gutter",
      font: THEME_FONT,
    },
  },
  {
    id: "tokyo-night-storm",
    family: "tokyo-night",
    label: "Storm",
    polarity: "dark",
    pair: "tokyo-night-day",
    license: "Apache-2.0",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
    swatches: {
      bg: "#24283b",
      bg_dark: "#1f2335",
      bg_highlight: "#292e42",
      fg: "#c0caf5",
      fg_dark: "#a9b1d6",
      fg_gutter: "#3b4261",
      comment: "#565f89",
      dark3: "#545c7e",
      dark5: "#737aa2",
      blue: "#7aa2f7",
      cyan: "#7dcfff",
      magenta: "#bb9af7",
      purple: "#9d7cd8",
      orange: "#ff9e64",
      yellow: "#e0af68",
      green: "#9ece6a",
      teal: "#1abc9c",
      red: "#f7768e",
      terminal_black: "#414868",
    },
    roles: {
      bg: "bg",
      card: "bg_dark",
      text: "fg",
      muted: "comment",
      accent: "blue",
      border: "fg_gutter",
      font: THEME_FONT,
    },
  },
  {
    id: "tokyo-night-moon",
    family: "tokyo-night",
    label: "Moon",
    polarity: "dark",
    pair: "tokyo-night-day",
    license: "Apache-2.0",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
    swatches: {
      bg: "#222436",
      bg_dark: "#1e2030",
      bg_highlight: "#2f334d",
      fg: "#c8d3f5",
      fg_dark: "#828bb8",
      fg_gutter: "#3b4261",
      comment: "#636da6",
      dark3: "#545c7e",
      dark5: "#737aa2",
      blue: "#82aaff",
      cyan: "#86e1fc",
      magenta: "#c099ff",
      purple: "#fca7ea",
      orange: "#ff966c",
      yellow: "#ffc777",
      green: "#c3e88d",
      teal: "#4fd6be",
      red: "#ff757f",
      terminal_black: "#444a73",
    },
    roles: {
      bg: "bg",
      card: "bg_dark",
      text: "fg",
      muted: "comment",
      accent: "blue",
      border: "fg_gutter",
      font: THEME_FONT,
    },
  },
  {
    id: "tokyo-night-day",
    family: "tokyo-night",
    label: "Day",
    polarity: "light",
    pair: "tokyo-night",
    license: "Apache-2.0",
    sourceUrl: "https://github.com/folke/tokyonight.nvim",
    swatches: {
      bg: "#e1e2e7",
      bg_dark: "#d0d5e3",
      bg_highlight: "#c4c8da",
      fg: "#3760bf",
      fg_dark: "#6172b0",
      fg_gutter: "#a8aecb",
      comment: "#848cb5",
      dark3: "#8990b3",
      dark5: "#68709a",
      blue: "#2e7de9",
      cyan: "#007197",
      magenta: "#9854f1",
      purple: "#7847bd",
      orange: "#b15c00",
      yellow: "#8c6c3e",
      green: "#587539",
      teal: "#118c74",
      red: "#f52a65",
      terminal_black: "#a1a6c5",
    },
    roles: {
      bg: "bg",
      card: "bg_dark",
      text: "fg",
      muted: "comment",
      accent: "blue",
      border: "fg_gutter",
      font: THEME_FONT,
    },
  },
];
